const constants= {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    GETDATA:'GETDATA',
    LOAD_SUCCESS:'LOAD_SUCCESS',
    REG_USER_REQUEST:'REG_USER_REQUEST',
    LOGIN_STATUS:'LOGIN_STATUS'
};

export default constants;